# Generated by Django 3.2.15 on 2022-09-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name2',
        ),
    ]
